//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegmentadorImagensMaldito.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int quadrosPorPagina {
            get {
                return ((int)(this["quadrosPorPagina"]));
            }
            set {
                this["quadrosPorPagina"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double porcentagemToleranciaDiferente {
            get {
                return ((double)(this["porcentagemToleranciaDiferente"]));
            }
            set {
                this["porcentagemToleranciaDiferente"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double porcentagemToleranciaIgual {
            get {
                return ((double)(this["porcentagemToleranciaIgual"]));
            }
            set {
                this["porcentagemToleranciaIgual"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double porcentagemMaximaDaImagemParaCobrirAntesDeJuntar {
            get {
                return ((double)(this["porcentagemMaximaDaImagemParaCobrirAntesDeJuntar"]));
            }
            set {
                this["porcentagemMaximaDaImagemParaCobrirAntesDeJuntar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int numeroLinhasParaAmostragemLinhaBase {
            get {
                return ((int)(this["numeroLinhasParaAmostragemLinhaBase"]));
            }
            set {
                this["numeroLinhasParaAmostragemLinhaBase"] = value;
            }
        }
    }
}
